### ISSUE TITLE
Support for JSON Schema anyOf and oneOf

### ISSUE THREAD

**Issue by nissimsan** [jiaoxlong/json-to-rdf-shacl#6]
We're working on finding the best representation on the LD side for JSON Schema's `anyOf` and `oneOf`: https://github.com/w3c-ccg/traceability-vocab/issues/527. 

Is this the same problem you are solving with https://github.com/jiaoxlong/jsc-ld/blob/main/jsc_ld_syntax.md#iddomain-idrange?

**Comment by jiaoxlong** [comment]
jsc-ld supports JSON schema composition (oneOf, anyOf, allOf, and not) to a certain extent. Our approach is to leave rdfs:range open for the properties have a composition schema in RDF vocabulary and specify data type constraints in SHACL. 

For example, 
```json
"bikes": {
    "ld.association": {
      "ld.id": "https://www.example.com/Bike",
    },
    "type": "object",
    "properties": {
        "bike_id": {
            "oneOf": [{ "type": "boolean" }, { "type": "number" }]
        },
        "is_broken":{"type": "boolean"}
    }
}
     
```
RDF vocabulary
```text
...
ex:bike_id rdf:type rdf:Property;
    rdfs:label "bike_id";
    rdfs:domain ex:Bike.
ex:is_broken rdf:type rdf:Property;
    rdfs:label "is_broken";
    rdfs:domain ex:Bike;
    rdfs:range xsd:boolean .
```
Note that there is **no** rdfs:range for ex:bike_id.

and SHACL
```code
...
[  
    sh:path ex:bike_id;
    sh:xone ([ sh:datatype xsd:boolean ] [ sh:datatype xsd:decimal ]) 
], 
[
    sh:path ex:is_broken;
    sh:datatype xsd:boolean
]
```
However, in your case, an array typed schema is wrapped inside a composition schema. Hmm, I do not have a solution yet.

```yml
type:
    oneOf:
      - type: array
        items:
          type: string
          enum:
            - DCSAShippingInstruction
      - type: string
        const:
          - DCSAShippingInstruction 
```
